### PR TITLE
several bugfixes

### PR DESCRIPTION
**Pull request by yevgmotov**
Fixes for:
#466 
#658 
#659 
#665 
#667 
#700 
#701 
#710 
#711 
#712

### CODE REVIEW

**Comment by yevgmotov** [comment]
@bskinner @Smartcop FYI

**Comment by bskinner** [comment]
@yevgmotov 
There are still outstanding issues with the field validations in the Building Services module on the iPad:

* Completely fill out form
* Tap into 'Location' or 'room' field and manually clear the value using the delete key.
* The search button becomes disabled
* The search button remains disabled after filling in the cleared fields until the email address is changed.

**Comment by yevgmotov** [comment]
@bskinner Not sure I understand the issue here. On iPad there's no 'search button'. When manually changing the 'Location' or 'room' fields, we get updated search results based on the entered text. If I completely clear the fields I get the default values in the popover. 

Maybe you can attach a screenshot of what you see?

**Comment by yevgmotov** [comment]
@bskinner Added one more bugfix in this PR. #700.

**Comment by yevgmotov** [comment]
Another add on to this pull request. bugfix #701

**Comment by bskinner** [comment]
@yevgmotov Whoops! That should be 'submit', not 'search'.

**Comment by yevgmotov** [comment]
@bskinner Is that reproducible for you? It works as expected on my iPad mini. When I delete location field manually and then enter text, the 'submit' button becomes enabled again.

**Comment by bskinner** [comment]
@yevgmotov 
Yep, been able to reproduce it very reliably:

* Fill out all fields so that the submit button is enabled
* Tap location field, using the 'delete' key on the keyboard, clear the field. The submit button will be disabled at this point.
* Resign the location field as the first responder
* Tap back into the 'location' field and tap on a new location
* Tap into the 'room' field and select a room

Expected result: The submit button should be enabled
Actual result: The submit button remains disabled even though all  the fields are completed.

**Comment by yevgmotov** [comment]
@bskinner Got it. Thanks for the steps to reproduce. Fixed.

**Comment by bskinner** [comment]
@yevgmotov Thanks! Reviewing everything now.

**Comment by bskinner** [comment]
@yevgmotov I noticed some odd rotation behavior relating to issue #658. I have added a screenshot to the issue showing the problem.

**Comment by yevgmotov** [comment]
@bskinner updated with fixes.

**Comment by bskinner** [comment]
@yevgmotov I'll get these merged in, then. Thank you!

**Pull request merged**
