### PR TITLE
Reworked UI handling of days with no meals #726

### PR DESCRIPTION
**Pull request by LoganWright**
#726 
#729

### CODE REVIEW

**Comment by LoganWright** [comment]
Closed because I thought I could do something a better way ... I could not.

**Comment by Smartcop** [comment]
@LoganWright 
Hello.  We would still like to be able to swipe left and right to view other days.

**Comment by LoganWright** [comment]
@Smartcop - I removed the logic that was specifying the current date and replaced it to use the dining day's date.  That should work if there are other days to view.

**Comment by Smartcop** [comment]
@LoganWright 
On production it does not work.  You can change the server settings in settings and then doing a two finger swipe to the left in the blank area.

**Comment by LoganWright** [comment]
@Smartcop - That's because there's no more dining days.  The same way that if you hit the end of the data on dev server, you can no longer swipe.  If there's no additional dining data, I don't think there's anything we can do.

**Comment by Smartcop** [comment]
@LoganWright 

We have just added a Open Sporadically Hall.  I cannot page but there are meals on "2015-01-12", "2015-01-14".

We would like the app to page by day and then by meal. Current it is only paging by meal.  

This should be looking at days that are in meals_by_day and then individuals meals in that day.

**Comment by justinanderson** [comment]
You can see it working in the current release of the app, 3.5.3. It pages by day and by meal.

**Comment by LoganWright** [comment]
@Smartcop - @justinanderson  - Ok, I'll look into changing the behavior to look at days first

**Comment by LoganWright** [comment]
@Smartcop @justinanderson  - Thanks for creating the 'Open Sporadically' restaurant -- made it much easier to test this!  It should be fix in the latest PR #747

**Pull request closed without merging**
